_core:
  default_config_hash: qSffC70ODbv0BehNMS_7K1sO34OogvBsnphKkBeV5W8
admin_css: true
decode: true
fx: ''
noscript: false
one_pixel: true
placeholder: /themes/custom/easydrupal/images/blank.svg
unstyled_extensions: ''
responsive_image: true
blazy:
  loadInvisible: true
  offset: 100
  saveViewportOffsetDelay: 50
  validateDelay: 25
  container: ''
io:
  enabled: true
  unblazy: false
  rootMargin: 0px
  threshold: '0'
  disconnect: false
