module:
  addtoany: 0
  admin_toolbar: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  advagg: 0
  advagg_cdn: 0
  advagg_css_minify: 0
  advagg_js_minify: 0
  advupdate: 0
  automated_cron: 0
  backup_migrate: 0
  big_pipe: 0
  blazy: 0
  block: 0
  block_content: 0
  bootstrap_layouts: 0
  breakpoint: 0
  captcha: 0
  ckeditor: 0
  config: 0
  contact: 0
  contact_storage: 0
  contextual: 0
  country: 0
  crop: 0
  ctools: 0
  ctools_views: 0
  datetime: 0
  dblog: 0
  devel: 0
  devel_php: 0
  disqus: 0
  ds_extras: 0
  ds_switch_view_mode: 0
  dynamic_page_cache: 0
  easydrupal_breadcrumb: 0
  easydrupal_common: 0
  editor: 0
  editor_advanced_link: 0
  entity_reference_revisions: 0
  fast404: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  file_mdm: 0
  filefield_paths: 0
  filter: 0
  geshifield: 0
  geshifilter: 0
  google_analytics: 0
  help: 0
  honeypot: 0
  image: 0
  image_widget_crop: 0
  imageapi_optimize: 0
  imageapi_optimize_webp: 0
  imagemagick: 0
  inline_form_errors: 0
  layout_discovery: 0
  libraries: 0
  link: 0
  linkit: 0
  media: 0
  menu_trail_by_path: 0
  menu_ui: 0
  metatag: 0
  metatag_google_plus: 0
  metatag_open_graph: 0
  metatag_twitter_cards: 0
  metatag_verification: 0
  metatag_views: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  purge: 0
  purge_processor_cron: 0
  purge_purger_http: 0
  purge_tokens: 0
  purge_ui: 0
  rabbit_hole: 0
  rdf: 0
  recaptcha: 0
  redirect: 0
  responsive_image: 0
  rh_node: 0
  rh_taxonomy: 0
  rh_user: 0
  schema_article: 0
  schema_metatag: 0
  schema_web_site: 0
  seckit: 0
  shortcut: 0
  simple_sitemap: 0
  slick: 0
  slick_ui: 0
  sophron: 0
  sticky_sharrre_bar: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  update: 0
  upgrade_status: 0
  user: 0
  views_bootstrap: 0
  views_infinite_scroll: 0
  views_ui: 0
  webp: 0
  yoast_seo: 0
  ds: 1
  extlink: 1
  menu_link_content: 1
  pathauto: 1
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  bootstrap: 0
  easydrupal: 0
  seven: 0
  claro: 0
_core:
  default_config_hash: m2GVq11UAOVuNgj8x0t5fMOPujpvQQ_zxLoaly1BMEU
langcode: en
profile: standard
