disabled: false
field_template: true
ft-default: minimal
ft-show-colon: false
classes:
  region:
    - row
    - col-sm-12
    - col-sm-4
    - col-sm-8
    - left-section
    - right-section
    - main-section
    - clearfix
  field: {  }
use_field_names: true
_core:
  default_config_hash: xfB0qOeoAomOThclNNokdKTrVwXLcXz13SU3-4a5-FY
