site_key: 6LdQuSYTAAAAAA-CWXloPpNrC9Rqr8sgz3aFssOg
secret_key: 6LdQuSYTAAAAAPvEOL34-07xZHjx3QElqoqwzD74
widget:
  theme: light
  type: image
  size: ''
  tabindex: 3
  noscript: false
_core:
  default_config_hash: ZKQ03ePk4sH2zESRw4tdZYw__nG2YN4Ru5roPL23g3A
